name = "fastapi"

compatibility_date = "2024-07-01"

[vars]

 UPSTASH_REDIS_REST_TOKEN  = 
 "AXeUASQgYjU2NWU2OWItZDZlOC00N2IxLWI0OGUtOWZlYjcxMz
NhYzU4NTllMmJjMmM1MGMyNGQyNjkwZmQ3YTJmYzA0YTc2MWQ="

 UPSTASH_REDIS_URL = "https://gusc1-together-buck-30612.upstash.io"